-- version 2019 03 06
CREATE INDEX DWH_DOCUMENT_TITLE_IDX ON DWH_DOCUMENT
(TITLE)
INDEXTYPE IS CTXSYS.CONTEXT
PARAMETERS('storage dwhstore stoplist dwh_stoplist lexer dwh_lexer')
NOPARALLEL;


CREATE INDEX DWH_TEXT_ENRICH_IDX ON DWH_TEXT
(ENRICH_TEXT)
INDEXTYPE IS CTXSYS.CONTEXT
PARAMETERS('storage dwhstore stoplist dwh_stoplist lexer dwh_lexer')
NOPARALLEL;


CREATE INDEX DWH_TEXT_IDX ON DWH_TEXT
(TEXT)
INDEXTYPE IS CTXSYS.CONTEXT
PARAMETERS('storage dwhstore stoplist dwh_stoplist_empty lexer dwh_lexer')
NOPARALLEL;


CREATE INDEX DWH_TEXT_TITLE_IDX ON DWH_TEXT
(TITLE)
INDEXTYPE IS CTXSYS.CONTEXT
PARAMETERS('storage dwhstore stoplist dwh_stoplist lexer dwh_lexer')
NOPARALLEL;

CREATE INDEX DWH_THESAURUS_DATA_DESCRI ON DWH_THESAURUS_DATA
(DESCRIPTION)
INDEXTYPE IS CTXSYS.CONTEXT
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_ENRSEM_STR ON DWH_THESAURUS_ENRSEM
(CONCEPT_STR)
INDEXTYPE IS CTXSYS.CONTEXT
NOPARALLEL;



CREATE INDEX DWH_THESAURUS_TAL_IDX ON DWH_THESAURUS_TAL
(CONCEPT_STR)
INDEXTYPE IS CTXSYS.CONTEXT
PARAMETERS('storage dwhstore stoplist dwh_stoplist lexer dwh_lexer')
NOPARALLEL;



CREATE INDEX DWH_COHORT_RESULT_CNUM_PNUM ON DWH_COHORT_RESULT
(COHORT_NUM, PATIENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_COHORT_RESULT_CNUM_STATUS ON DWH_COHORT_RESULT
(COHORT_NUM, STATUS)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DATA_DNUM ON DWH_DATA
(DOCUMENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DATA_I ON DWH_DATA
(THESAURUS_DATA_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DATA_III ON DWH_DATA
(THESAURUS_CODE, THESAURUS_DATA_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DATA_IIII ON DWH_DATA
(THESAURUS_DATA_NUM, PATIENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DATAMART_RES_1 ON DWH_DATAMART_RESULT
(DATAMART_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DATA_PNUM ON DWH_DATA
(PATIENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DEMANDE_ACCES_I ON DWH_REQUEST_ACCESS
(USER_NUM_REQUEST)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DEMANDE_ACCES_II ON DWH_REQUEST_ACCESS
(USER_NUM_REQUEST, MANAGER_AGREEMENT)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DEMANDE_ACCES_III ON DWH_REQUEST_ACCESS
(REQUEST_ACCESS_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DEMANDE_ACCES_PATIENT_I ON DWH_REQUEST_ACCESS_PATIENT
(REQUEST_ACCESS_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DEMANDE_ACCES_PATIENT_II ON DWH_REQUEST_ACCESS_PATIENT
(REQUEST_ACCESS_NUM, PATIENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DOCUMENT_ENRGENE ON DWH_DOCUMENT
(ENRGENE_DONE_FLAG)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DOCUMENT_ENRSEM ON DWH_DOCUMENT
(EXTRACTCONCEPT_DONE_FLAG)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DOCUMENT_IDDOC_PNUM ON DWH_DOCUMENT
(DOCUMENT_NUM, PATIENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DOCUMENT_IDSOURCE_ORIGIN ON DWH_DOCUMENT
(ID_DOC_SOURCE, DOCUMENT_ORIGIN_CODE)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DOCUMENTIEP_I ON DWH_DOCUMENT
(ENCOUNTER_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DOCUMENT_NEW_IDDOC ON DWH_DOCUMENT
(DOCUMENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DOCUMENT_ORIGINCODE ON DWH_DOCUMENT
(DOCUMENT_ORIGIN_CODE)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DOCUMENT_PNUM ON DWH_DOCUMENT
(PATIENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DOCUMENT_SERVICE_II ON DWH_DOCUMENT
(DEPARTMENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DOCUMENT_SERVICE_PNUM ON DWH_DOCUMENT
(DEPARTMENT_NUM, PATIENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_DOCUMENT_UNIT_CODE ON DWH_DOCUMENT
(UNIT_CODE)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_ENRSEM_CONCERTCOD ON DWH_ENRSEM
(CONTEXT, CERTAINTY, CONCEPT_CODE)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_ENRSEM_CONTEXT ON DWH_ENRSEM
(CONTEXT)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_ENRSEM_DOCUMENT_NUM ON DWH_ENRSEM
(DOCUMENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_ENRSEM_GROUPBYPATCODE ON DWH_ENRSEM
(PATIENT_NUM, CONCEPT_CODE)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_ENRSEM_PATIENT_NUM ON DWH_ENRSEM
(PATIENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_ENRSEM_PK ON DWH_ENRSEM
(ENRSEM_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_FILE_I ON DWH_FILE
(DOCUMENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_CITY ON DWH_PATIENT
(PATIENT_NUM, RESIDENCE_CITY, RESIDENCE_LONGITUDE, RESIDENCE_LATITUDE)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_I ON DWH_PATIENT
(UPPER("LASTNAME"))
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_II ON DWH_PATIENT
(UPPER("LASTNAME"||' '||"FIRSTNAME"))
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_III ON DWH_PATIENT
(UPPER("FIRSTNAME"||' '||"LASTNAME"))
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_IPPHIST_I ON DWH_PATIENT_IPPHIST
(PATIENT_NUM, MASTER_PATIENT_ID)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_IPPHIST_II ON DWH_PATIENT_IPPHIST
(ORIGIN_PATIENT_ID)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_IPPHIST_III ON DWH_PATIENT_IPPHIST
(HOSPITAL_PATIENT_ID)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_IPPHIST_PNUM ON DWH_PATIENT_IPPHIST
(PATIENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_LOG_PNUM ON DWH_LOG_PATIENT
(USER_NUM, PATIENT_NUM, LOG_CONTEXT)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_MAPPING ON DWH_PATIENT
( REGEXP_REPLACE (UPPER(CONVERT("LASTNAME",'US7ASCII')),'[^A-Z]',''))
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_MVT_E ON DWH_PATIENT_MVT
(ENCOUNTER_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_MVT_PAT ON DWH_PATIENT_MVT
(PATIENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_MVT_PE ON DWH_PATIENT_MVT
(PATIENT_NUM, ENCOUNTER_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_MVT_PEO ON DWH_PATIENT_MVT
(PATIENT_NUM, ENCOUNTER_NUM, MVT_ORDER)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_NUM ON DWH_PATIENT
(PATIENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_NUM_PAYS ON DWH_PATIENT
(PATIENT_NUM, BIRTH_COUNTRY)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_PNUM_SERVICE ON DWH_PATIENT_DEPARTMENT
(PATIENT_NUM, DEPARTMENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_REL_I ON DWH_PATIENT_REL
(PATIENT_NUM_1)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_REL_II ON DWH_PATIENT_REL
(PATIENT_NUM_2)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_REL_III ON DWH_PATIENT_REL
(PATIENT_NUM_2, RELATION)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_SERVICE_I ON DWH_PATIENT_DEPARTMENT
(DEPARTMENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_SERVICE_II ON DWH_PATIENT_DEPARTMENT
(PATIENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_STAT_PATIENT_NUM ON DWH_PATIENT_STAT
(PATIENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_STAY_I ON DWH_PATIENT_STAY
(ENCOUNTER_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_STAY_PNUM ON DWH_PATIENT_STAY
(PATIENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PATIENT_UPCITY ON DWH_PATIENT
(REPLACE(UPPER("RESIDENCE_CITY"),' ',''))
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PROCESS_I ON DWH_PROCESS
(PROCESS_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PROCESS_PATIENT_I ON DWH_PROCESS_PATIENT
(PROCESS_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PROFILE_DOCUMENT_ORIGIN ON DWH_PROFILE_DOCUMENT_ORIGIN
(USER_PROFILE)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_PROFILE_RIGHT_USER ON DWH_PROFILE_RIGHT
(USER_PROFILE)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE UNIQUE INDEX DWH_QUERY_PK ON DWH_QUERY
(QUERY_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_TEXT_AGE ON DWH_TEXT
(CERTAINTY, CONTEXT, TRUNC("AGE_PATIENT"))
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_TEXT_CER_CON_PATIENT_NUM ON DWH_TEXT
(CERTAINTY, CONTEXT, PATIENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_TEXT_CONTEXT ON DWH_TEXT
(CONTEXT)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_TEXT_CTX_CERT ON DWH_TEXT
(CONTEXT, CERTAINTY)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_TEXT_DEPNUM ON DWH_TEXT
(DEPARTMENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;



CREATE INDEX DWH_TEXT_IDX1 ON DWH_TEXT
(DOCUMENT_NUM, CONTEXT, CERTAINTY)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_TEXT_IDX2 ON DWH_TEXT
(CERTAINTY)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_TEXT_NEW_I ON DWH_TEXT
(DOCUMENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_TEXT_ORIGINDOC ON DWH_TEXT
(DOCUMENT_ORIGIN_CODE)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_TEXT_PATIENT_NUM ON DWH_TEXT
(PATIENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;





CREATE INDEX DWH_THESAURUS_CITY ON DWH_THESAURUS_CITY
(COUNTRY, CITY_NORM_NAME)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_CITY_COUNTRY ON DWH_THESAURUS_CITY
(COUNTRY)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_DATA_GRAPH_I ON DWH_THESAURUS_DATA_GRAPH
(THESAURUS_DATA_FATHER_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_DATA_GRAPH_II ON DWH_THESAURUS_DATA_GRAPH
(THESAURUS_DATA_FATHER_NUM, THESAURUS_DATA_SON_NUM, THESAURUS_CODE)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_DATA_GRAPH_III ON DWH_THESAURUS_DATA_GRAPH
(THESAURUS_DATA_FATHER_NUM, THESAURUS_CODE, DISTANCE, THESAURUS_DATA_SON_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_DATA_GRAPH_IIII ON DWH_THESAURUS_DATA_GRAPH
(THESAURUS_CODE, THESAURUS_DATA_SON_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_DATA_I ON DWH_THESAURUS_DATA
(CONCEPT_CODE)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_DATA_THE_NUM ON DWH_THESAURUS_DATA
(THESAURUS_CODE, THESAURUS_DATA_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_DATA_TPNUM ON DWH_THESAURUS_DATA
(THESAURUS_PARENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_ENRSEM_CCODE ON DWH_THESAURUS_ENRSEM
(CONCEPT_CODE)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_ENRSEM_CCO_LSTR ON DWH_THESAURUS_ENRSEM
(CONCEPT_CODE, LOWER("CONCEPT_STR"))
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_ENRSEMGENO ON DWH_THESAURUS_ENRSEM
(GENOTYPE)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_ENRSEM_GRAPH ON DWH_THESAURUS_ENRSEM_GRAPH
(CONCEPT_CODE_SON, CONCEPT_CODE_FATHER)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_ENRSEM_GRAPH_I ON DWH_THESAURUS_ENRSEM_GRAPH
(CONCEPT_CODE_FATHER)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_ENRSEM_GRAPH_II ON DWH_THESAURUS_ENRSEM_GRAPH
(DISTANCE, CONCEPT_CODE_FATHER, CONCEPT_CODE_SON)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_ENRSEM_GRAPH_III ON DWH_THESAURUS_ENRSEM_GRAPH
(CONCEPT_CODE_FATHER, CONCEPT_CODE_SON)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_ENRSEM_GRAPH_4 ON DWH_THESAURUS_ENRSEM_GRAPH
(CONCEPT_CODE_FATHER, DISTANCE, CONCEPT_CODE_SON)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_ENRSEM_I ON DWH_THESAURUS_ENRSEM
(CONCEPT_CODE, PREF, PHENOTYPE)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_ENRSEM_II ON DWH_THESAURUS_ENRSEM
(CONCEPT_CODE, PREF)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_ENRSEMPHENO ON DWH_THESAURUS_ENRSEM
(PHENOTYPE)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;

CREATE INDEX DWH_THESAURUS_PUBMED_GENE ON DWH_THESAURUS_PUBMED_GENE
(CUI, GENEID)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_PUBMED_GENE2GOI ON DWH_THESAURUS_PUBMED_GENE2GO
(EVIDENCE, CATEGORY, QUALIFIER)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_PUBMED_GENE2GOII ON DWH_THESAURUS_PUBMED_GENE2GO
(GENEID)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_TAL_CLIB ON DWH_THESAURUS_TAL
(LOWER("CONCEPT_STR"))
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_TAL_V2_I ON DWH_THESAURUS_TAL
(CONCEPT_CODE)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_TYPESEMANTIC_I ON DWH_THESAURUS_TYPESEMANTIC
(SEMANTIC_TYPE)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_UNIT_I ON DWH_THESAURUS_UNIT
(DEPARTMENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_UNIT_II ON DWH_THESAURUS_UNIT
(UNIT_CODE)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_THESAURUS_UNIT_III ON DWH_THESAURUS_UNIT
(UNIT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_TMP_RESULT_1 ON DWH_TMP_PRERESULT
(QUERY_KEY, USER_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;

CREATE INDEX DWH_TMP_QUERY_I ON DWH_TMP_QUERY
(QUERY_KEY, USER_NUM, DATAMART_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_TMP_RESULT_II ON DWH_TMP_RESULT
(TMPRESULT_NUM, DOCUMENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_TMP_RESULT_PNUM ON DWH_TMP_RESULT
(PATIENT_NUM, TMPRESULT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_TMP_RESULT_PNUM_I ON DWH_TMP_RESULT
(TMPRESULT_NUM, PATIENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_USER_DEPARTMENT_I ON DWH_USER_DEPARTMENT
(USER_NUM, DEPARTMENT_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_USER_I ON DWH_USER
(LOGIN)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_USER_ONLINE_I ON DWH_USER_ONLINE
(USER_NUM, DATABASE)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_USER_PROFILE_II ON DWH_USER_PROFILE
(USER_NUM, USER_PROFILE)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;


CREATE INDEX DWH_USER_PROFIL_I ON DWH_USER_PROFILE
(USER_NUM)
LOGGING
TABLESPACE TS_IDX
NOPARALLEL;



CREATE INDEX DWH_DOC_UPLOAD_ID ON DWH_DOCUMENT 
(SUBSTR(UPLOAD_ID,1,8)) 
TABLESPACE TS_IDX;

CREATE INDEX DWH_DOC_ORIG_UPLOAD_ID ON DWH_DOCUMENT 
(DOCUMENT_ORIGIN_CODE,SUBSTR(UPLOAD_ID,1,8)) 
TABLESPACE TS_IDX;


create index dwh_patient_opposition_i on dwh_patient_opposition (patient_num) tablespace ts_idx;

create index dwh_data_minmaxdate on dwh_data (thesaurus_data_num,to_number(to_char(document_date,'YYYY'))) tablespace ts_idx

