-- create user as sys dba
CREATE USER DWH
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE TS_DWH
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for DWH 
  GRANT RESOURCE TO DWH;
  GRANT CONNECT TO DWH;
  ALTER USER DWH DEFAULT ROLE ALL;
  -- 3 System Privileges for DWH 
  GRANT UNLIMITED TABLESPACE TO DWH;
  GRANT CREATE SYNONYM TO DWH;
  GRANT CREATE ANY DIRECTORY TO DWH;
  -- 41 Object Privileges for DWH 
    GRANT EXECUTE ON CTXSYS.CTX_CLS TO DWH;
    GRANT EXECUTE ON CTXSYS.CTX_DDL TO DWH;

-- Tablespace for the data (default)
CREATE BIGFILE TABLESPACE TS_DWH DATAFILE 
  '/your_path/ts_dwh' SIZE 265200M AUTOEXTEND ON NEXT 100M MAXSIZE 34359738344K
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

-- Tablespace for the index 
CREATE BIGFILE TABLESPACE TS_IDX DATAFILE 
  '/your_path/tablespace_idx' SIZE 102400M AUTOEXTEND ON NEXT 100M MAXSIZE 34359738344K
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
